openapi: 3.0.0
info:
  title: Runas OpenAPI Specification
  version: 0.0.1
servers:
  - description: Test server, local
    url: localhost:8080
tags:
  - name: dictionary
    description: Access the dictionary data
paths:
  /spelling:
    summary: Access spellings stored in the dictionary
    description: Access spellings, i.e. grpahical representations of a 'word'
    get:
      description: List all spellings
      tags:
        - dictionary
      responses:
        200:
          description: Here are your spellings

  /spelling/{id}:
    get:
      tags:
        - dictionary
      responses:
        200: {}
        404: {}
